#!/usr/bin/env bash

# Build the runtime views of the canonical skills tree.
#
# Claude and Gemini can use directory symlinks directly. Codex follows those
# symlinks recursively during catalog discovery, so it instead receives one
# generated, shallow wrapper directory for each root skill.

set -euo pipefail

usage() {
    printf 'Usage: %s <ai-bootstrap-dir>\n' "$(basename "$0")" >&2
    printf '       %s --catalog-manifest <ai-bootstrap-dir>\n' "$(basename "$0")" >&2
}

mode="link"
case "${1-}" in
    --catalog-manifest)
        if [ "$#" -ne 2 ]; then
            usage
            exit 2
        fi
        mode="catalog-manifest"
        ai_bootstrap_arg="$2"
        ;;
    --help|-h)
        if [ "$#" -ne 1 ]; then
            usage
            exit 2
        fi
        usage
        exit 0
        ;;
    *)
        if [ "$#" -ne 1 ]; then
            usage
            exit 2
        fi
        ai_bootstrap_arg="$1"
        ;;
esac

if [ ! -d "$ai_bootstrap_arg" ]; then
    printf 'Missing AI bootstrap directory: %s\n' "$ai_bootstrap_arg" >&2
    exit 1
fi

ai_bootstrap_dir="$(cd "$ai_bootstrap_arg" && pwd -P)"
skills_dir="$ai_bootstrap_dir/skills"
codex_dir="$ai_bootstrap_dir/.codex"
codex_skills_dir="$codex_dir/skills"
gemini_skills_dir="$ai_bootstrap_dir/.gemini/skills"
gemini_antigravity_skills_dir="$ai_bootstrap_dir/.gemini/antigravity/skills"
claude_skills_dir="$ai_bootstrap_dir/.claude/skills"
projection_marker=".codex-skill-projection"
projection_format="format=codex-skill-projection-v1"
projection_comment="<!-- Generated by ai-bootstrap/scripts/link-ai-skills.sh. Do not edit. -->"
declare -a temporary_directories=()

if [ ! -d "$skills_dir" ]; then
    printf 'Missing canonical skills directory: %s\n' "$skills_dir" >&2
    exit 1
fi

cleanup_temporary_directories() {
    local status=$?
    local directory

    for directory in "${temporary_directories[@]}"; do
        [ -d "$directory" ] && rm -rf -- "$directory"
    done

    return "$status"
}
trap cleanup_temporary_directories EXIT

log_info() {
    printf '%s\n' "$*"
}

log_error() {
    printf '%s\n' "$*" >&2
}

skill_path_depth() {
    local relative_path="${1#"$skills_dir"/}"
    local depth=0

    while [[ "$relative_path" == */* ]]; do
        relative_path="${relative_path#*/}"
        ((depth += 1))
    done

    printf '%s\n' "$depth"
}

# Pick one canonical source directory for each catalog name. Shallower paths
# win regardless of find traversal order; equal-depth collisions use a stable
# lexical tiebreaker. The manifest records every losing source. Directories
# named subskills, archive, or .system are deliberately pruned.
declare -A skill_map=()
declare -A skill_collision_losers=()

record_collision_loser() {
    local skill_name="$1"
    local loser="${2#"$ai_bootstrap_dir"/}"
    local current="${skill_collision_losers[$skill_name]-}"

    if [ -n "$current" ]; then
        skill_collision_losers["$skill_name"]+=$'\n'"$loser"
    else
        skill_collision_losers["$skill_name"]="$loser"
    fi
}

build_skill_map() {
    local skill_file skill_dir skill_name existing_dir candidate_depth existing_depth

    skill_map=()
    skill_collision_losers=()
    while IFS= read -r -d '' skill_file; do
        skill_dir="$(dirname "$skill_file")"
        skill_name="$(basename "$skill_dir")"

        existing_dir="${skill_map[$skill_name]-}"
        if [ -z "$existing_dir" ]; then
            skill_map["$skill_name"]="$skill_dir"
            continue
        fi

        candidate_depth="$(skill_path_depth "$skill_dir")"
        existing_depth="$(skill_path_depth "$existing_dir")"
        if ((candidate_depth < existing_depth)) || { ((candidate_depth == existing_depth)) && [[ "$skill_dir" < "$existing_dir" ]]; }; then
            record_collision_loser "$skill_name" "$existing_dir"
            skill_map["$skill_name"]="$skill_dir"
        else
            record_collision_loser "$skill_name" "$skill_dir"
        fi
    done < <(find "$skills_dir" \
        -type d \( -name .git -o -name node_modules -o -name tests \
            -o -name fixtures -o -name assets -o -name subskills \
            -o -name archive -o -name .system \) -prune \
        -o -type f -name "SKILL.md" -print0)
}

skill_ownership() {
    local skill_dir="$1"
    local candidate_dir="$skill_dir"

    while [ "$candidate_dir" != "$skills_dir" ]; do
        if [ -e "$candidate_dir/.git" ]; then
            printf 'submodule\n'
            return
        fi
        candidate_dir="$(dirname "$candidate_dir")"
    done

    printf 'repo\n'
}

emit_catalog_manifest() {
    local skill_name skill_dir relative_dir ownership collision_losers

    {
        for skill_name in "${!skill_map[@]}"; do
            skill_dir="${skill_map[$skill_name]}"
            relative_dir="${skill_dir#"$ai_bootstrap_dir"/}"
            ownership="$(skill_ownership "$skill_dir")"
            collision_losers="${skill_collision_losers[$skill_name]-}"
            printf '%s\0%s\0%s\0%s\0' "$skill_name" "$relative_dir" "$ownership" "$collision_losers"
        done
    } | python3 -c '
import json
import sys

fields = sys.stdin.buffer.read().split(b"\0")
if fields and fields[-1] == b"":
    fields.pop()
if len(fields) % 4:
    raise SystemExit("catalog manifest generation failed")
entries = [
    {
        "name": fields[index].decode("utf-8"),
        "source": fields[index + 1].decode("utf-8"),
        "ownership": fields[index + 2].decode("utf-8"),
        "collision_losers": sorted(filter(None, fields[index + 3].decode("utf-8").splitlines())),
    }
    for index in range(0, len(fields), 4)
]
print(json.dumps({
    "schema_version": 1,
    "selection_rule": "shallowest path, then lexical path",
    "excluded_names": [],
    "collisions": [
        {
            "name": entry["name"],
            "winner": entry["source"],
            "losers": entry["collision_losers"],
        }
        for entry in entries
        if entry["collision_losers"]
    ],
    "surfaces": [
        ".claude/skills",
        ".codex/skills",
        ".gemini/skills",
        ".gemini/antigravity/skills",
    ],
    "skills": sorted(entries, key=lambda entry: entry["name"]),
}, indent=2, sort_keys=True))
'
}

copy_frontmatter() {
    local source_skill="$1"
    local destination="$2"

    awk '
        NR == 1 {
            if ($0 != "---") {
                exit 2
            }
            in_frontmatter = 1
        }
        in_frontmatter {
            print
            if (NR > 1 && $0 == "---") {
                complete = 1
                exit
            }
        }
        END {
            if (!complete) {
                exit 3
            }
        }
    ' "$source_skill" > "$destination"
}

is_managed_skill_symlink() {
    local entry="$1"
    local link_target

    [ -L "$entry" ] || return 1
    link_target="$(readlink "$entry")" || return 1
    [[ "$link_target" == "$skills_dir/"* ]]
}

is_managed_codex_wrapper() {
    local entry="$1"
    local marker="$entry/$projection_marker"
    local skill_file="$entry/SKILL.md"
    local first_line
    local second_line
    local third_line
    local source_path

    [ -d "$entry" ] && [ ! -L "$entry" ] || return 1
    [ -f "$marker" ] && [ -f "$skill_file" ] || return 1
    grep -Fqx -- "$projection_comment" "$skill_file" || return 1

    first_line="$(sed -n '1p' "$marker")"
    second_line="$(sed -n '2p' "$marker")"
    third_line="$(sed -n '3p' "$marker")"
    [ "$first_line" = "$projection_format" ] || return 1
    [[ "$second_line" == source=* ]] || return 1
    [ -z "$third_line" ] || return 1

    source_path="${second_line#source=}"
    [[ "$source_path" == "$skills_dir/"* ]]
}

report_unmanaged_collision() {
    local tool_name="$1"
    local target="$2"

    log_error "Refusing to replace unmanaged $tool_name skill entry: $target"
    log_error "Move or remove it explicitly, then rerun this installer."
    return 1
}

write_codex_wrapper() {
    local skill_name="$1"
    local source_dir="$2"
    local source_skill="$source_dir/SKILL.md"
    local target_dir="$codex_skills_dir/$skill_name"
    local staging_dir

    if [ -L "$target_dir" ] && ! is_managed_skill_symlink "$target_dir"; then
        report_unmanaged_collision "Codex" "$target_dir"
        return 1
    fi
    if [ -e "$target_dir" ] && [ ! -L "$target_dir" ] && ! is_managed_codex_wrapper "$target_dir"; then
        report_unmanaged_collision "Codex" "$target_dir"
        return 1
    fi

    staging_dir="$(mktemp -d "$codex_dir/.skill-projection.$skill_name.XXXXXX")"
    temporary_directories+=("$staging_dir")
    if ! copy_frontmatter "$source_skill" "$staging_dir/SKILL.md"; then
        log_error "Codex skill $skill_name has no complete YAML frontmatter: $source_skill"
        return 1
    fi

    printf '%s\n' \
        '' \
        "$projection_comment" \
        '' \
        'This is a catalog-only Codex adapter.' \
        '' \
        "Before using this skill, read the canonical source in full: $source_skill" \
        '' \
        'Treat that canonical file and its linked resources as the complete, authoritative instructions.' \
        'Do not infer missing instructions from this adapter.' >> "$staging_dir/SKILL.md"
    printf '%s\nsource=%s\n' "$projection_format" "$source_skill" > "$staging_dir/$projection_marker"

    # Do not remove a working managed entry until the replacement has passed
    # frontmatter validation and is fully written outside the catalog tree.
    if [ -L "$target_dir" ]; then
        if ! is_managed_skill_symlink "$target_dir"; then
            report_unmanaged_collision "Codex" "$target_dir"
            return 1
        fi
        rm -f -- "$target_dir"
    elif [ -e "$target_dir" ]; then
        if ! is_managed_codex_wrapper "$target_dir"; then
            report_unmanaged_collision "Codex" "$target_dir"
            return 1
        fi
        rm -rf -- "$target_dir"
    fi

    mv -- "$staging_dir" "$target_dir"
}

link_direct_skill() {
    local source_dir="$1"
    local target_dir="$2"
    local tool_name="$3"

    if [ -L "$target_dir" ]; then
        if ! is_managed_skill_symlink "$target_dir"; then
            report_unmanaged_collision "$tool_name" "$target_dir"
            return 1
        fi
    elif [ -e "$target_dir" ]; then
        report_unmanaged_collision "$tool_name" "$target_dir"
        return 1
    fi

    ln -sfn "$source_dir" "$target_dir"
}

remove_stale_direct_skill() {
    local entry="$1"
    local target_dir="$2"
    local entry_name

    entry_name="$(basename "$entry")"
    if is_managed_skill_symlink "$entry"; then
        rm -f -- "$entry"
        log_info "Removed stale skill: $entry_name from $(basename "$(dirname "$target_dir")")"
    else
        log_info "Keeping unmanaged skill entry: $entry_name"
    fi
}

remove_stale_codex_skill() {
    local entry="$1"
    local entry_name

    entry_name="$(basename "$entry")"
    if is_managed_codex_wrapper "$entry"; then
        rm -rf -- "$entry"
        log_info "Removed stale Codex skill projection: $entry_name"
    elif is_managed_skill_symlink "$entry"; then
        rm -f -- "$entry"
        log_info "Removed stale Codex skill symlink: $entry_name"
    else
        log_info "Keeping unmanaged Codex skill entry: $entry_name"
    fi
}

build_skill_map

if [ "$mode" = "catalog-manifest" ]; then
    emit_catalog_manifest
    exit 0
fi

mkdir -p \
    "$codex_skills_dir" \
    "$gemini_skills_dir" \
    "$gemini_antigravity_skills_dir" \
    "$claude_skills_dir"

declare -A expected_skills
for skill_name in "${!skill_map[@]}"; do
    skill_dir="${skill_map[$skill_name]}"
    expected_skills["$skill_name"]=1

    write_codex_wrapper "$skill_name" "$skill_dir"
    link_direct_skill "$skill_dir" "$gemini_skills_dir/$skill_name" "Gemini"
    link_direct_skill "$skill_dir" "$gemini_antigravity_skills_dir/$skill_name" "Gemini Antigravity"
    link_direct_skill "$skill_dir" "$claude_skills_dir/$skill_name" "Claude"
done

for target_dir in \
    "$codex_skills_dir" \
    "$gemini_skills_dir" \
    "$gemini_antigravity_skills_dir" \
    "$claude_skills_dir"; do
    [ -d "$target_dir" ] || continue
    for entry in "$target_dir"/*; do
        [ -e "$entry" ] || [ -L "$entry" ] || continue
        entry_name="$(basename "$entry")"
        [ -n "${expected_skills[$entry_name]+x}" ] && continue

        if [ "$target_dir" = "$codex_skills_dir" ]; then
            remove_stale_codex_skill "$entry"
        else
            remove_stale_direct_skill "$entry" "$target_dir"
        fi
    done
done
